### ISSUE TITLE
Change ETH to ZEBRO

### ISSUE THREAD

**Issue by ZebroTech** [web3labs/sirato-free#59]
Explorer is working fine.
Is it possible to change logo to own logo and Coin 'ETH' to custom name 'ZEBRO'?
Thanks

**Comment by cfelde** [comment]
Hi, this is part of our SaaS offering, check it out: https://www.web3labs.com/sirato

**Comment by ZebroTech** [comment]
> Hi, this is part of our SaaS offering, check it out: https://www.web3labs.com/sirato

got it,
Is there any way I pay once off for branding and run sirato script locally without bridging?
Thanks

**Comment by cfelde** [comment]
Some clients require on-prem, which is doable, but that would still require SaaS type licensing costs. Feel free to reach out to me on christian@web3labs.com if you'd like to discuss details.

**Comment by ZebroTech** [comment]
> Some clients require on-prem, which is doable, but that would still require SaaS type licensing costs. Feel free to reach out to me on [christian@web3labs.com](mailto:christian@web3labs.com) if you'd like to discuss details.

I will test this free trial then contact you after discussing with my team.
